# Update download package, core for upgrading, site core version and content, RSS, test.html
# Site content (what's new etc) in the main repo should be updated manually before running this
name: update site for a new release from sources repo

on:
  workflow_dispatch:
    inputs:
      # 
      committerName:
        description: "Username for commit"
        required: true
      committerEmail:
        description: "User email for commit"
        required: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      # todo:
      # - add step: build and copy tiddlywiki_externaljs.html, twcore.js, jQuery.twStylesheet.js, jquery.js
      # - test the whole scenario, remove the logging bits, enable committing
      - uses: actions/checkout@v2
      - name: config git
        run: |
          git config --global user.name ${{ github.event.inputs.committerName }}
          git config --global user.email ${{ github.event.inputs.committerEmail }}
      - name: get TiddlyWiki source and install dependencies
        run: |
          git clone https://github.com/TiddlyWiki/TiddlyWiki.git
          cd TiddlyWiki
          npm i
      # looks like each new step cwd is changed back to the "root"
      - name: build index.html, index.xml (RSS), move and stage resulting files
        run: |
          cd TiddlyWiki
          npm run build-site
          # generating index.html may fail (on Ubuntu, unlike on Windows), so use wildcards
          mv ./build/cooked/*/* ../
          cd ..
          git add *
          # test bits to be removed:
          git status
      - name: build empty TW, copy resulting file as empty.html, upgrade/index.html, stage them
        run: |
          cd TiddlyWiki
          npm run build-core
          cp ./build/cooked/*/empty.html ../
          cp ./build/cooked/*/empty.html ../upgrade/index.html
          cd ..
          git add empty.html upgrade/index.html
      - name: build tests.html, move resulting file, stage it
        run: |
          cd TiddlyWiki
          npm run build-test
          mv ./build/cooked/*/test.html ../tests.html
          cd ..
          git add tests.html
      - name: commit and push result
        run: |
          cd ./TiddlyWiki
          package=$(cat package.json)
          version=$(node -pe 'JSON.parse(process.argv[1]).version' "$package")
          cd ..
          echo "update site to v$version (index.html?, index.xml?, empty.html, upgrade/index.html, test.html, ___)"
          git status
          # git commit -m "update site to v$version (index.html, index.xml, empty.html, upgrade/index.html, test.html, ___)"
          # git push
