# Update download package, core for upgrading, site core version and content, RSS, test.html
# Site content (what's new etc) in the main repo should be updated manually before running this
name: update site for a new release from sources repo

on:
  workflow_dispatch:
    inputs:
      # 
      committerName:
        description: "Username for commit"
        required: true
      committerEmail:
        description: "User email for commit"
        required: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      # todo:
      # - fix: build-site fails on Ubuntu (unlike on Windows)
      # - test the whole scenario, remove the logging bits, enable committing
      - uses: actions/checkout@v2
      - name: config git
        run: |
          git config --global user.name ${{ github.event.inputs.committerName }}
          git config --global user.email ${{ github.event.inputs.committerEmail }}
      - name: get TiddlyWiki source and install dependencies
        run: |
          git clone https://github.com/TiddlyWiki/TiddlyWiki.git
          cd ./TiddlyWiki
          # temp fix attempt
          npm install tiddlywiki@5.1.21
          npm i
          # - name: build index.html, index.xml (RSS), move and stage resulting files
          #   run: |
          npm run build-site
          mv ./build/cooked/*/index.html ../
          mv ./build/cooked/*/index.xml ../
          git add ../index.html
          git add ../index.xml
          # test bits to be removed:
          echo "index.html's head:"
          head -n 7 ../index.html
          echo "index.xml:"
          cat ../index.xml
      - name: build empty TW, copy resulting file as empty.html, upgrade/index.html, stage them
        run: |
          npm run build-core
          cp ./build/cooked/*/empty.html ../
          cp ./build/cooked/*/empty.html ../upgrade/index.html
          git add ../empty.html ../upgrade/index.html
          # test bits to be removed:
          echo "empty.html's and upgrade/index.html's heads:"
          head -n 7 ../empty.html
          head -n 7 ../upgrade/index.html
      - name: build tests.html, move resulting file, stage it
        run: |
          npm run build-test
          mv ./build/cooked/*/test.html ../tests.html
          git add ../tests.html
          # test bits to be removed:
          echo "test.html's head:"
          head -n 7 ../tests.html
      # todo: build and copy tiddlywiki_externaljs.html, twcore.js, jQuery.twStylesheet.js, jquery.js
      - name: commit and push result
        run: |
          package=$(cat package.json)
          version=$(node -pe 'JSON.parse(process.argv[1]).version' "$package")
          cd ..
          echo "update site to v$version (index.html, empty.html, upgrade/index.html, test.html, ___)"
          # git commit -m "update site to v$version (index.html, empty.html, upgrade/index.html, test.html, ___)"
          # git push
