# Update download package, core for upgrading, site core version and content, RSS, test.html
# Site content (what's new etc) in the main repo should be updated manually before running this
name: update site for a new release from sources repo

on:
  workflow_dispatch:
    inputs:
      # 
      committerName:
        description: "Username for commit"
        required: true
      committerEmail:
        description: "User email for commit"
        required: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      # todo:
      # - fix: build-site (RSS generation) fails on Ubuntu (unlike on Windows)
      #  - test other steps: do they work ok?
      # - test the whole scenario, remove the logging bits, enable committing
      - uses: actions/checkout@v2
      - name: config git
        run: |
          git config --global user.name ${{ github.event.inputs.committerName }}
          git config --global user.email ${{ github.event.inputs.committerEmail }}
      - name: get TiddlyWiki source and install dependencies
        run: |
          git clone https://github.com/TiddlyWiki/TiddlyWiki.git
          cd ./TiddlyWiki
          npm i
          # not sure why separating into steps breaks things yet (todo: rename the merged step)
          # - name: build empty TW, copy resulting file as empty.html, upgrade/index.html, stage them
          #   run: |
          npm run build-core
          cp ./build/cooked/*/empty.html ../
          cp ./build/cooked/*/empty.html ../upgrade/index.html
          cd ..
          git add empty.html upgrade/index.html
          cd -
          # - name: build tests.html, move resulting file, stage it
          #   run: |
          npm run build-test
          mv ./build/cooked/*/test.html ../tests.html
          cd ..
          git add tests.html
          cd -
          # # - name: build index.html, index.xml (RSS), move and stage resulting files
          # #   run: |
          # npm run build-site
          # mv ./build/cooked/*/index.html ../
          # mv ./build/cooked/*/index.xml ../
          # git add ../index.html
          # git add ../index.xml
          # # test bits to be removed:
          # echo "index.html's head:"
          # head -n 7 ../index.html
          # echo "index.xml:"
          # cat ../index.xml
      # todo: build and copy tiddlywiki_externaljs.html, twcore.js, jQuery.twStylesheet.js, jquery.js
      - name: commit and push result
        run: |
          cd ./TiddlyWiki
          package=$(cat package.json)
          version=$(node -pe 'JSON.parse(process.argv[1]).version' "$package")
          cd ..
          echo "update site to v$version (index.html, empty.html, upgrade/index.html, test.html, ___)"
          # git commit -m "update site to v$version (index.html, index.xml, empty.html, upgrade/index.html, test.html, ___)"
          # git push
